language: php
php:
  - 5.3

before_script:
  - composer install --dev --prefer-dist
script:
  - ./vendor/bin/phpcpd --log-pmd=./build/logs/pmd-cpd.xml --exclude=./tests --progress -v ./app/classes/
  - ./vendor/bin/phpunit --coverage-clover=./build/logs/clover.xml

notifications:
  email: false